version: '3.8'

services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.5.1
    container_name: filebeat
    user: root
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/log:/var/log
    restart: always
