version: '3.8'

services:
  apache:
    image: httpd:latest
    ports:
      - "8080:8080"
    volumes:
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./www:/var/www/html
    restart: always

  mysql-slave:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: securepassword
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - mysql-data:/var/lib/mysql
    restart: always

volumes:
  mysql-data:
