version: '3.7'

services:
  # Сервисы для VM1
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend
    extra_hosts:  # Добавляем явное разрешение имен
      - "apache2:192.168.140.133"

  apache1:
    image: httpd:latest
    networks:
      - backend
    ports:
      - "8080:80"  # Меняем порт для избежания конфликта
    volumes:
      - ./apache1_html:/usr/local/apache2/htdocs  # Для тестовой страницы

  mysql_master:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
      MYSQL_REPLICATION_USER: repl_user
      MYSQL_REPLICATION_PASSWORD: repl_password
    volumes:
      - mysql_master_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend

  # Сервисы для VM2
  apache2:
    image: httpd:latest
    networks:
      - backend
    extra_hosts:
      - "apache1:192.168.140.132"
    ports:
      - "8080:80"  # Меняем порт для избежания конфликта
    volumes:
      - ./apache2_html:/usr/local/apache2/htdocs  # Для тестовой страницы

  mysql_slave:
    # ... (остается без изменений)
  
  # Сервисы для VM3
  # ... (остается без изменений)

networks:
  backend:
    driver: bridge
    attachable: true

volumes:
  mysql_master_data:
  mysql_slave_data:
  elk_data:
