version: '3.7'

services:
  # Сервисы для VM1
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      backend:
        aliases:
          - nginx.vm1

  apache1:
    image: httpd:latest
    ports:
      - "8081:80"  # Измененный порт для Apache1
    networks:
      backend:
        aliases:
          - apache1.vm1

  mysql_master:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
      MYSQL_REPLICATION_USER: repl_user
      MYSQL_REPLICATION_PASSWORD: repl_password
    volumes:
      - mysql_master_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      backend:
        aliases:
          - mysql.vm1

  # Сервисы для VM2
  apache2:
    image: httpd:latest
    ports:
      - "8082:80"  # Измененный порт для Apache2
    networks:
      backend:
        aliases:
          - apache2.vm2
    depends_on:
      - mysql_master

  mysql_slave:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_MASTER_HOST: mysql.vm1  # Используем алиас
      MYSQL_MASTER_USER: repl_user
      MYSQL_MASTER_PASSWORD: repl_password
      MYSQL_MASTER_PORT: 3306
    volumes:
      - mysql_slave_data:/var/lib/mysql
    networks:
      backend:
        aliases:
          - mysql.vm2

  # Сервисы для VM3
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      backend:
        aliases:
          - prometheus.vm3

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      backend:
        aliases:
          - grafana.vm3

  elk:
    image: sebp/elk:latest
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - elk_data:/var/lib/elasticsearch
    networks:
      backend:
        aliases:
          - elk.vm3

networks:
  backend:
    driver: bridge
    attachable: true 
    ipam:
      config:
        - subnet: 192.168.140.0/24
    
volumes:
  mysql_master_data:
  mysql_slave_data:
  elk_data:
