---
- name: Install Filebeat
  apt:
    name: filebeat
    state: present

- name: Configure Filebeat
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml

- name: Enable system module
  command: filebeat modules enable system

- name: Start Filebeat
  service:
    name: filebeat
    state: started
    enabled: yes
