---
- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - docker.io
    - docker-compose
    - python3-pip

- name: Ensure Docker is running
  service:
    name: docker
    state: started
    enabled: yes
