---
- name: Create nginx directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /opt/nginx/conf
    - /opt/nginx/logs

- name: Deploy nginx config
  template:
    src: nginx.conf.j2
    dest: /opt/nginx/conf/nginx.conf

- name: Run nginx container
  docker_container:
    name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /opt/nginx/logs:/var/log/nginx
    restart_policy: always
