---
- hosts: all
  roles:
    - common

- hosts: loadbalancer
  roles:
    - nginx

- hosts: app_servers
  roles:
    - mysql_master

- hosts: monitoring
  roles:
    - mysql_slave
    - elk
    - filebeat
