---
- hosts: all
  become: yes
  roles:
    - common

- hosts: loadbalancer
  become: yes
  roles:
    - nginx

- hosts: app_servers
  become: yes
  roles:
    - mysql_master

- hosts: monitoring
  become: yes
  roles:
    - mysql_slave
    - elk
    - filebeat
