version: '3.8'

services:
  apache:
    image: httpd:latest
    container_name: apache
    ports:
      - "8080:80"
    volumes:
      - ./index.html:/usr/local/apache2/htdocs/index.html
    restart: always
